### ISSUE TITLE
Postfix problems

### ISSUE THREAD

**Issue by kingbenja** [kaltura/platform-install-packages#327]
I am very new to Kaltura installations. I managed to get it working as far as i can tell but Kaltura is unable to send emails. During install i started postfix service as recommended. Are there further configurations i need to do to get it running?

**Comment by KalturaCommunity** [comment]
Hi,

Please start by running:
# mail -s Test yourmail@domain.com </etc/issue

Lets see if you get that, if not, this is not a problem with Kaltura but a 
general problem.
If so, look at /var/log/maillog for errors.

I am closing the issue because the 'issues' section should only contain 
bug reports and not general questions, for future questions, please post 
at forum.kaltura.org.

Thanks,

May the source be with you,

Jess Portnoy
