### ISSUE TITLE
DB failure

### ISSUE THREAD

**Issue by kingbenja** [kaltura/platform-install-packages#328]
I keep getting this error message at configuration
Connectivity test passed:)ERROR: Couldn't make an API request to http://myhostname.com:80/api_v3/index.php?service=system&action=ping.Please check your setup and then run /opt/kaltura/bin/kaltura-db-config.sh again.
I have tried this

service mysqld stop
rm -rf /var/lib/mysql
yum reinstall mysql-server
service mysqld start
mysql_secure_installation

and it still doesn't work. Runing the install on Centos6 on GCE:

**Comment by jessp01** [comment]
Hi,

The issue here has no direct connection to DB, apart from the fact that in order to populate the DB, access to the REST API is needed.
If you do:
\# curl http://myhostname.com:80/api_v3/index.php?service=system&action=ping -I -v
It will also fail, this is probably because myhostname.com is not resolvable or else because there is a FW. Of course, it can be for other reasons but these are the most common.
