### ISSUE TITLE
General cluster question?

### ISSUE THREAD

**Issue by nukepuppy** [kaltura/platform-install-packages#365]
If we have a dedicated large mysql server..

using the CHEF recipes
does a specific SERVER need to exist for DWH?  OR do we just need to run the recipe to get the DWH database setup? (i dont understand the role of DWH if its an application or just some backend database system?)  If we need an application can there be 2? what happens if 2 machines run the DWH recipe.

Along the same lines.. VOD packager  can there be more than 1? what happens when VOD recipe is run on 2 machines.

we're using S3 for storage btw if that helps to narrow down some of the questions. I been led to believe this would not require NFS?

**Comment by jessp01** [comment]
Hello,

DWH is the MySQL DB to retain the analytics for views, plays, etc. It is a separate DB than the operational 'kaltura' MySQL DB but they can both reside on the same MySQL server. Although THEY CAN reside on separate ones as well if you prefer.

Only one machine should run the DWH recipe. And of course, you should create a replication node for it, much like you need to do for the operational 'kaltura' DB.

VOD Packager - you can have several such nodes with an LB between them.

You can try to use S3 for your shared space between Kaltura nodes but personally, I would recommend going with NFS. While it has been a long time since we last tried such integration, it proved to be rather slow and once it stopped working altogether cause of a strange file name created on it, which made the XML returned when questioning the S3 file system corrupt. Again, this was several years ago, perhaps things are better now. Using S3 to store the videos only is fine, we have a lot of deployments out there that do exactly that.

I am closing this issue but if you have more questions, please post at forum.kaltura.org.

**Comment by nukepuppy** [comment]
Jess, thanks for your response.

I sitll don't understand DWH though...  WHO should run the DWH recipe if i have a dedicated mysql server?   does it matter who since DWH will just be a dedicated mysql server? like RDS for example

is DWH just going to then 'seed' some data? and then its done.. similar to db_config?

sorry ill take it to forum for other stuff

**Comment by KalturaCommunity** [comment]
Hi && welcome,

DWH - this is a two parter really:
0. The DB which holds that data
1. The scripts used to collect the stats from the Apache access logs and 
place it in the DB

The DB is created when running kaltura-db-config.sh and is populated when 
running kaltura-dwh-config.sh.

Then it is updated every day by running these cron jobs:
/opt/kaltura/app/configurations/cron/dwh

A symlink to /etc/cron.d/kaltura-dwh is created during the run of 
/opt/kaltura/bin/kaltura-dwh-config.sh:
67 ln -sf $APP_DIR/configurations/cron/dwh /etc/cron.d/kaltura-dwh

This happens as part of the DWH recipe.

Hope its clearer now,

May the source be with you,

Jess Portnoy

**Comment by nukepuppy** [comment]
Much clearer..  but one last thing would be

If using a centralized DB and desiring redundancy..
can the DWH SCRIPTS be run on 2 machines?  (not the database part) just the scripts crons etc?

that is only real part confusing me.. and if they cannot how does one add redundancy to DWH services?

**Comment by KalturaCommunity** [comment]
You cannot run these scripts from two machines, it will actually cause a 
sever malfunction. If the node running them fails, you can always run 
kaltura-dwh-config.sh on another node. The data will not be lost since it 
is retained in the access log under /opt/kaltura/web/logs which is shared 
between fronts and batches.

May the source be with you,

Jess Portnoy
