### ISSUE TITLE
Kaltura CE 10 - analytics error

### ISSUE THREAD

**Issue by vadimtar** [kaltura/platform-install-packages#374]
Hi,

I'm receiving the following error from the analytics logs:

ERROR 04-04 23:00:24,815 - hourly - A serious error occurred during job execution: org.pentaho.di.core.exception.KettleException:
Unexpected error occurred while launching entry [Register etl_server.0]

Unexpected error during transformation metadata load

Unable to read file [file:///root/${EtlBasePath}/common/register_etl_server.ktr]
Could not read from "file:///root/${EtlBasePath}/common/register_etl_server.ktr" because it is a not a file.

**Comment by jessp01** [comment]
Did the deployment phase of kaltura-dwh-config.sh complete successfully? I suggest you use:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.8.0/RPM/scripts/postinst/drop-dwh-data.sh

To drop the Analytics data and then rerun kaltura-dwh-config.sh. Note that you will lose any stats you already had if you do so but if this is a clean deployment it does not matter.

I am closing the github issue since this does not seem like a general bug, for specific issues, please post at forum.kaltura.org

Thanks,
