### ISSUE TITLE
Update to ffmpeg 2.6.3 with support libx265

### ISSUE THREAD

**Issue by jniltinho** [kaltura/platform-install-packages#408]
ffmpeg Kaltura is 2.1

http://programster.blogspot.com.br/2014/08/h265-its-amazing.html

Ubuntu 14.04
High Efficiency Video Coding (HEVC)

sudo add-apt-repository ppa:samrog131/ppa -y
sudo apt-get update
sudo apt-get install ffmpeg-real -y

/opt/ffmpeg/bin/ffmpeg -version

**Comment by jessp01** [comment]
Not sure I understand your comment.
We provide our own FFMPEG build for a reason. We require specific compilation options and also test it quite a bit. Also, our code needs to match the version since their API changes between versions.
It is not recommended to replace FFMPEG with your own, even if it comes from the official repo.
