### ISSUE TITLE
Missing dependencies in Debian 8

### ISSUE THREAD

**Issue by bangerer** [kaltura/platform-install-packages#414]
Hi everyone!

I tried to install Kaltura Platform in Debian 8 today by following your installation instructions[1].
Unfortunately the package installation can't be completed due to missing dependencies.

My package manager (aptitude) tells me the following packages are not available in Debian 8:
- "mencoder" (dependency of "kaltura-batch" 10.12.0-1+b1)
- "libass4" (dependency of "kaltura-ffmpeg" 2.1.3-1+b20)
- "libopenjpeg2" (also dependency of "kaltura-ffmpeg" 2.1.3-1+b20)

Refreshing the package cache didn't help much, so I went to Debian's package search[2] and was able to confirm those packages are indeed missing in the official repositories.

Possible substitutes I found were:
- "mencoder" (from the unofficial Deb-Multimedia repository[3])
- "libass5" (included in Debian's official repository)
- "libopenjpeg5" (also included in Debian's official repository)

Hope I didn't miss something in the documentation or the issue tracker, but:
What are my options?
(If possible, I'd like to avoid adding additional repositories, switching the distro or downgrading. ;) )

Thanks :)
- Bernie

--

Some additional info about my setup:

Output of "lsb_release -a":
Distributor ID: Debian
Description:    Debian GNU/Linux 8.1 (jessie)
Release:        8.1
Codename:       jessie

Output of "uname -a":
Linux kaltura-test 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

Contents of "/etc/apt/sources.list":
deb http://ftp.debian.org/debian/ jessie main contrib non-free
deb http://security.debian.org/ jessie/updates main contrib non-free
deb http://installrepo.kaltura.org/repo/apt/debian jupiter main

--

References

[1] https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-deb-based.md
[2] https://www.debian.org/distrib/packages#search_packages
[3] http://www.deb-multimedia.org/

**Comment by kaltura-hooks** [comment]
Hi @bangerer,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If self hosted, provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hello,

Please see 
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.14.0/doc/install-kaltura-deb-based.md:
Debian Jessie [8] NOTE: You must also make sure the following are enabled 
in /etc/apt/sources.list

deb htp://ftp.debian.org/debian/ wheezy main
deb htp://security.debian.org/ wheezy/updates main

Thanks,

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
virtualconnect.kaltura.com

**Comment by bangerer** [comment]
Hi Jess,

thanks a lot - now it works.
(Thought "wheezy" aka Debian 7 was a typo in that context. ;) )

- Bernie

**Comment by KalturaCommunity** [comment]
Hello,

Happy it works.
I saw a typo with 'htp' instead of 'http', is that the one you're 
referring to? if it is - just fixed:)

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
virtualconnect.kaltura.com

**Comment by bangerer** [comment]
Hi!

Oh well, I wrongly assumed the two lines...

deb http://ftp.debian.org/debian/ wheezy main
deb http://security.debian.org/ wheezy/updates main

... should actually read...

deb http://ftp.debian.org/debian/ jessie main
deb http://security.debian.org/ jessie/updates main

... and seeing those last two lines were already present in my "sources.list", I skipped that part of the install guide altogether. Which was an error on my part. :)

Anyway, thanks for your help - and for fixing the other typo with "htp" as well.

- Bernie

**Comment by KalturaCommunity** [comment]
Changed it to:
Debian Jessie [8] NOTE: You must also make sure the following Wheezy repos 
are enabled in /etc/apt/sources.list

In hope it will help others.

Thanks,

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
virtualconnect.kaltura.com
