### ISSUE TITLE
Deb8 install kaltura-front unmet dependencies: ffmpeg

### ISSUE THREAD

**Issue by fluxcorenz** [kaltura/platform-install-packages#416]
Just trying to install kaltura on a fresh debian 8 install today, and following the instructions fine until installing the kaltura-front package.

Met with:

```
The following packages have unmet dependencies:
 kaltura-ffmpeg : Depends: libfdk-aac0 which is a virtual package.
                  Depends: libfaac0 which is a virtual package.
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     kaltura-ffmpeg [Not Installed]
2)     kaltura-front [Not Installed]
```

Continuing on is untenable, as kaltura-front is left uninstalled.

I have previously added the two wheezy apt sources as instructed, so it's not missing due to that. 

I notice there's another issue relating to ffmpeg licensing, so apologies if it's currently uninstallable due to that.

**Comment by kaltura-hooks** [comment]
Hi @fluxcorenz,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by fluxcorenz** [comment]
It appears that 'jessie non-free' is a required package source for these libs - it would be good to update the documentation with that information :)

**Comment by KalturaCommunity** [comment]
Will do, thanks:)
All deps resolved?


May the source be with you,

Jess Portnoy



-------- Original message --------

**Comment by fluxcorenz** [comment]
Yep, deps resolved, however when installing kaltura-batch I got:

```
The following packages have unmet dependencies:
 libdvdnav4 : Breaks: mencoder (< 2:1.0) but 2:1.0~rc4.dfsg1+svn34540-1+deb7u1 is to be installed.
              Breaks: mplayer (< 2:1.0) but 2:1.0~rc4.dfsg1+svn34540-1+deb7u1 is to be installed.
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     kaltura-batch [Not Installed]
2)     mencoder [Not Installed]
3)     mplayer [Not Installed]

Accept this solution? [Y/n/q/?] 
```

I answered 'n' and then got:

```
The following actions will resolve these dependencies:

     Install the following packages:
1)     libdvdnav4 [4.2.0+20120524-2 (oldstable)]
```

Which I accepted.

So it looks like possibly jessie is providing competing packages?

**Comment by KalturaCommunity** [comment]
Will look into.
Thanks for reporting.


May the source be with you,

Jess Portnoy



-------- Original message --------

**Comment by jessp01** [comment]
Hi @fluxcorenz,

This would happen on Jessie cause indeed there are newer versions of some packages. Thing is, we want it to work on older versions as well and this is the reason for it.
If it had not been for the mencoder and mplayer being install on your ENV it would not have asked to resolve anything. This is not to say its not legit to have these packages installed of course but our platform does not need them:)

I also added a note about the need for non-free and referenced your report.

Thank you for that.
