### ISSUE TITLE
dwh log permissions incorrect

### ISSUE THREAD

**Issue by fluxcorenz** [kaltura/platform-install-packages#417]
After a fresh install on debian 8, mail gets generated from the cron script regarding insufficient permissions to the dwh log files:

```
/opt/kaltura/dwh/etlsource/execute/etl_hourly.sh: line 20: /opt/kaltura/dwh/logs/etl_hourly-20150703-10.log: Permission denied
```

The cron task is run as user 'kaltura', however the directory and log files are only owned by root, files with 644 permissions:

```
root@kaltura:/opt/kaltura/dwh/logs# ls -alh
total 300K
drwxr-xr-x  2 root root 4.0K Jul  3 10:09 .
drwxr-xr-x 14 root root 4.0K Jul  2 17:26 ..
-rw-r--r--  1 root root 1.3K Jul  2 17:37 dwh_setup.log
-rw-r--r--  1 root root  71K Jul  3 10:09 etl_daily-20150703.log
-rw-r--r--  1 root root  62K Jul  3 10:09 etl_hourly-20150703-10.log
-rw-r--r--  1 root root 7.8K Jul  3 10:09 etl_update_dims-20150703-10.log
-rw-r--r--  1 root root 8.4K Jul  3 10:09 log_aggregation_perform_aggregations.log
-rw-r--r--  1 root root  53K Jul  3 10:09 log_events_events.log
-rw-r--r--  1 root root  63K Jul  3 10:09 log_perform_referential_integrity.log
-rw-r--r--  1 root root 1.8K Jul  3 10:09 log_storage_usage_calc_storage_usage.log
-rw-r--r--  1 root root  634 Jul  3 10:09 log_transcoding_usage_calc_transcoding_usage.log
-rw-r--r--  1 root root   12 Jul 20  2014 README.txt
```

I'm not sure whether it is more correct to chown+chmod the log directory and files to the kaltura user, or to run the cron as root (obviously the former is preferred!)

**Comment by kaltura-hooks** [comment]
Hi @fluxcorenz,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Thank you @fluxcorenz.
You are most correct. Fix pushed.
Please obtain kaltura-dwh_10.10.0-1+b11
Might be a few minutes before the package is synced to all CDN edges.

**Comment by jessp01** [comment]
Sorry, take kaltura-dwh_10.10.0-1+b12.
Small typo in 11's postinst
