### ISSUE TITLE
Installation problems on RedHat 7.1

### ISSUE THREAD

**Issue by jdwolfe** [kaltura/platform-install-packages#421]
Installing from a new AWS instance from the AMI RHEL-7.1_HVM_GA-20150225-x86_64-1-Hourly2-GP2 (ami-12663b7a)

Following the instructions on https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md
When doing `sudo yum install kaltura-server` it fails with 
```
--> Finished Dependency Resolution
Error: Package: kaltura-mencoder-3.4.6-9.x86_64 (Kaltura)
           Requires: liboil-0.3.so.0
Error: Package: php-mbstring-5.4.16-23.el7_0.3.x86_64 (Kaltura)
           Requires: php-common(x86-64) = 5.4.16-23.el7_0.3
           Installed: php-common-5.4.16-36.el7_1.x86_64 (@rhui-REGION-rhel-server-releases)
               php-common(x86-64) = 5.4.16-36.el7_1
           Available: php-common-5.4.16-21.el7.x86_64 (rhui-REGION-rhel-server-releases)
               php-common(x86-64) = 5.4.16-21.el7
           Available: php-common-5.4.16-23.el7_0.x86_64 (rhui-REGION-rhel-server-releases)
               php-common(x86-64) = 5.4.16-23.el7_0
           Available: php-common-5.4.16-23.el7_0.1.x86_64 (rhui-REGION-rhel-server-releases)
               php-common(x86-64) = 5.4.16-23.el7_0.1
           Available: php-common-5.4.16-23.el7_0.3.x86_64 (rhui-REGION-rhel-server-releases)
               php-common(x86-64) = 5.4.16-23.el7_0.3
Error: Package: kaltura-batch-10.14.0-1.noarch (Kaltura-noarch)
           Requires: mediainfo
Error: Package: kaltura-front-10.14.0-1.noarch (Kaltura-noarch)
           Requires: mediainfo
```

I searched for one of the missing packages
```
$ sudo yum search liboil
Loaded plugins: amazon-id, rhui-lb
=========================================================================== N/S matched: liboil ===========================================================================
liboil.x86_64 : Library of Optimized Inner Loops, CPU optimized functions
```
and tried to installed it
```
 sudo yum install liboil.x86_64
Loaded plugins: amazon-id, rhui-lb
Resolving Dependencies
--> Running transaction check
---> Package liboil.x86_64 0:0.3.16-10.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================================================================
 Package                                Arch                                   Version                                       Repository                               Size
===========================================================================================================================================================================
Installing:
 liboil                                 x86_64                                 0.3.16-10.el7                                 Kaltura                                 127 k

Transaction Summary
===========================================================================================================================================================================
Install  1 Package

Total download size: 127 k
Installed size: 573 k
Is this ok [y/d/N]: y
Downloading packages:
warning: /var/cache/yum/x86_64/7Server/Kaltura/packages/liboil-0.3.16-10.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY B/s | 124 kB  --:--:-- ETA
Public key for liboil-0.3.16-10.el7.x86_64.rpm is not installed
liboil-0.3.16-10.el7.x86_64.rpm                                                                                                                     | 127 kB  00:00:01
Retrieving key from http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
Importing GPG key 0xBA443EF2:
 Userid     : "Kaltura (for RPMs.) <community@kaltura.com>"
 Fingerprint: 1688 ff2e af8e d7b6 ecba a36b b194 baa5 ba44 3ef2
 From       : http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
Is this ok [y/N]: y


Public key for liboil-0.3.16-10.el7.x86_64.rpm is not installed


 Failing package is: liboil-0.3.16-10.el7.x86_64
 GPG Keys are configured as: http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
```

The public key isn't installed to download this package?

**Comment by kaltura-hooks** [comment]
Hi @jdwolfe,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Just resigned it. Can you please change kaltura.repo to take from installrepo.origin.kaltura.org instead of installrepo.kaltura.org? Cause it will be a  while till CDN edges are all synced...

May the source be with you,

Jess Portnoy



On Wed, Jul 8, 2015 at 3:32 PM -0700, "Jeff Wolfe" <notifications@github.com<mailto:notifications@github.com>> wrote:


Installing from a new AWS instance from the AMI RHEL-7.1_HVM_GA-20150225-x86_64-1-Hourly2-GP2 (ami-12663b7a)

Following the instructions on https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md
When doing sudo yum install kaltura-server it fails with

--> Finished Dependency Resolution
Error: Package: kaltura-mencoder-3.4.6-9.x86_64 (Kaltura)
           Requires: liboil-0.3.so.0
Error: Package: php-mbstring-5.4.16-23.el7_0.3.x86_64 (Kaltura)
           Requires: php-common(x86-64) = 5.4.16-23.el7_0.3
           Installed: php-common-5.4.16-36.el7_1.x86_64 (@rhui-REGION-rhel-server-releases)
               php-common(x86-64) = 5.4.16-36.el7_1
           Available: php-common-5.4.16-21.el7.x86_64 (rhui-REGION-rhel-server-releases)
               php-common(x86-64) = 5.4.16-21.el7
           Available: php-common-5.4.16-23.el7_0.x86_64 (rhui-REGION-rhel-server-releases)
               php-common(x86-64) = 5.4.16-23.el7_0
           Available: php-common-5.4.16-23.el7_0.1.x86_64 (rhui-REGION-rhel-server-releases)
               php-common(x86-64) = 5.4.16-23.el7_0.1
           Available: php-common-5.4.16-23.el7_0.3.x86_64 (rhui-REGION-rhel-server-releases)
               php-common(x86-64) = 5.4.16-23.el7_0.3
Error: Package: kaltura-batch-10.14.0-1.noarch (Kaltura-noarch)
           Requires: mediainfo
Error: Package: kaltura-front-10.14.0-1.noarch (Kaltura-noarch)
           Requires: mediainfo


I searched for one of the missing packages

$ sudo yum search liboil
Loaded plugins: amazon-id, rhui-lb
=========================================================================== N/S matched: liboil ===========================================================================
liboil.x86_64 : Library of Optimized Inner Loops, CPU optimized functions


and tried to installed it

 sudo yum install liboil.x86_64
Loaded plugins: amazon-id, rhui-lb
Resolving Dependencies
--> Running transaction check
---> Package liboil.x86_64 0:0.3.16-10.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================================================================
 Package                                Arch                                   Version                                       Repository                               Size
===========================================================================================================================================================================
Installing:
 liboil                                 x86_64                                 0.3.16-10.el7                                 Kaltura                                 127 k

Transaction Summary
===========================================================================================================================================================================
Install  1 Package

Total download size: 127 k
Installed size: 573 k
Is this ok [y/d/N]: y
Downloading packages:
warning: /var/cache/yum/x86_64/7Server/Kaltura/packages/liboil-0.3.16-10.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY B/s | 124 kB  --:--:-- ETA
Public key for liboil-0.3.16-10.el7.x86_64.rpm is not installed
liboil-0.3.16-10.el7.x86_64.rpm                                                                                                                     | 127 kB  00:00:01
Retrieving key from http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
Importing GPG key 0xBA443EF2:
 Userid     : "Kaltura (for RPMs.) <community@kaltura.com>"
 Fingerprint: 1688 ff2e af8e d7b6 ecba a36b b194 baa5 ba44 3ef2
 From       : http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
Is this ok [y/N]: y


Public key for liboil-0.3.16-10.el7.x86_64.rpm is not installed


 Failing package is: liboil-0.3.16-10.el7.x86_64
 GPG Keys are configured as: http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura


The public key isn't installed to download this package?

-

**Comment by jessp01** [comment]
Hello,

Can this be closed?

Thanks,

**Comment by jessp01** [comment]
Closing this one. In the event you're still having issues, please let me know.
