### ISSUE TITLE
Yum repository for RHEL7/CentOS7 is unavailable.

### ISSUE THREAD

**Issue by morpheus3205** [kaltura/platform-install-packages#429]
Your yum repository for RHEL7/CentOS7 (  http://installrepo.kaltura.org/releases/rhel7/RPMS/.. ) is not usable. "noarch" under rhel7/RPMS/ is not a directory but a single file ( 08-Jul-2015 13:35  43M ). Please check.

**Comment by jessp01** [comment]
The noarch is here:
http://installrepo.origin.kaltura.org/releases/stable/RPMS/noarch
since there is no reason to keep one per dist version.

Your repo file should look like this:
[Kaltura]
name = Kaltura Server
baseurl = http://installrepo.kaltura.org/releases/rhel7/RPMS/$basearch/
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1
enabled = 1

[Kaltura-noarch]
name = Kaltura Server arch independent
baseurl = http://installrepo.kaltura.org/releases/stable/RPMS/noarch
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1
enabled = 1
 
This is also reflected in the documentation:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.17.0/doc/install-kaltura-redhat-based.md#note-on-rhelcentos-7

**Comment by morpheus3205** [comment]
Understood. Thanks.
