### ISSUE TITLE
libass4 missing in Debian 8, why not use libass5?

### ISSUE THREAD

**Issue by JHGitty** [kaltura/platform-install-packages#471]
While installing Kaltura we found 2 issues:

```
Die folgenden Pakete haben verletzte Abhängigkeiten:
 kaltura-ffmpeg : Hängt ab von: libass4 ist aber nicht installierbar.
                  Hängt ab von: libopenjpeg2 ist aber nicht installierbar.
```

We have "libass5" in the repository of Debian 8 but not "libass4".
We have "libopenjpeg5" in the repo of Debian 8 but not "libopenjpeg2".

Can you allow the other libraries or are they not compatible?

**Comment by Huskynarr** [comment]
:+1: Same here. :P

**Comment by KalturaCommunity** [comment]
Please see:
https://github.com/kaltura/platform-install-packages/blob/Kajam-11.0.0/doc/install-kaltura-deb-based.md#setup-the-kaltura-deb-repository

Since we want one repo that works for both 7 and 8, as well as for Ubuntu, 
the code is linked against a lower version.
However, you can add the wheezy repos which should be fine for you.

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by JHGitty** [comment]
Why not add both libraries as allowed libraries?

**Comment by KalturaCommunity** [comment]
Because they are not binary compatible.

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]
