### ISSUE TITLE
KMC$ panel is blank after log in

### ISSUE THREAD

**Issue by iwaninfor** [kaltura/platform-install-packages#481]
I am already installed succesfully kaltura lates version on centos 6.x. when i am login in KMC4, i have blank page.

![kaltura_kmc4](https://cloud.githubusercontent.com/assets/1614767/10775259/7063b718-7d39-11e5-9627-8851a7338be2.jpg)

Some body can help me??

Regard's

Iwan

**Comment by zoharbabin** [comment]
@iwaninfor - can you open the Chrome or Firefox network monitor and see if you're getting any errors?
Also - do you have Flash installed? KMC uses Flash.

**Comment by iwaninfor** [comment]
I have installed flash on my PC and I am already open using firefox and chrome and the result is same

Regard's

Iwan setiawan

**Comment by zoharbabin** [comment]
@iwaninfor can you please use the Chrome Network view and Console to see if there are any errors (unloaded files, JS errors, etc.); https://developer.chrome.com/devtools

**Comment by jessp01** [comment]
Hello,

My first guess would be your provided a hostname that is not resolvable. When prompted by the install for service URL, Apache hostname and all other hostname prompts, you must supply something that is resolvable from both within the Kaltura server [as it is making HTTP requests to itself] and the machine from which you are running the browser.

You can easily verify this by using your browser's dev tools and looking at the network tab, you will most probably see a 404 upon requesting the kmc.swf.

I am closing this issue since we'd like to use the issues section exclusively for general bug reports. Please post at forum.kaltura.org for general questions and troubleshooting help.

Thanks,
