### ISSUE TITLE
Documentation for services on each component or role

### ISSUE THREAD

**Issue by nukepuppy** [kaltura/platform-install-packages#486]
We need to find what services run for each component.
For troubleshooting/monitoring/documentation/restart procedures/disaster recovery purposes I think this would be ideal.

As in Frontend server:
/etc/init.d/httpd start?
what else?

sphinx ?

dwh?

batch ?

**Comment by nukepuppy** [comment]
even on second look the chef cookbooks don't seem to even enforce starting/running the processes or services so it's extremely difficult to document this properly

**Comment by jessp01** [comment]
Hello,

Seeing how several roles can be installed on the same machine, it varies but basically:
Any node that serves a web I/F [Admin console, KMC] needs Apache, any node that uses itself to make API calls, i,e any node that has SERVICE_URL=$PROTOCOL://`hostname` needs Apache as well.

Any node that has batch installed needs the kaltura-batch daemon running.
Any node that has sphinx on it needs kaltura-sphinx and kaltura-populate, the latter being use to sync between Sphinx instances.
All batch and front/API nodes should have memcached running.

Only one node needs to have kaltura-dwh installed and it runs no daemons. Its operation is done via cronjobs defined in /etc/cron.d/kaltura-dwh

Chef does not start any daemons itself because they are either started on the RPM's postinst or by the configure script.

Hope that helps, for additional inquiries please post to forum.kaltura.org.

Thanks,
