### ISSUE TITLE
kaltura-html5lib package comes with multiple version of that library

### ISSUE THREAD

**Issue by wzur** [kaltura/platform-install-packages#492]
kaltura-html5lib comes with multiple version of that library.
I'd expect either separate RPMs for each version (much like Tomcat6, Tomcat7, etc) or no duplication at all. This package has grown to more than 1GB and with this model it will grow further with no end.

**Comment by jessp01** [comment]
Hello,

The issue stems for the fact the uiconf for each player contain a specific HTML5lib version.
Thus, if the player was created when, for instance, v2.26 was the current version, it will stop working if this version is removed.
In addition, there are external projects that expect certain player versions, for instance, Mediaspace.

Releasing a separate RPM/deb package per version is also not that good because, unlike Tomcat for instance, a new player version is introduced every other week and, so, if we were to do it that way, you'll just end up with kaltura-html5libv2.6-2.6, kaltura-html5libv2.7-2.7, kaltura-html5libv2.8-2.8 and so on. Where the version will have to be included in the package name so that it does not get deleted during an upgrade. That is also not scaleable and look incoherent.

What we really need to do is periodically update the uiconfs to look at the latest version, which will enable us to get rid of older versions.

We will discuss such a strategy internally.

I hope this helps to explain why things are as they are.

Thanks for commenting.

**Comment by jessp01** [comment]
One more important note, while there is a need for multiple versions, what takes most of the space is this:
https://github.com/kaltura/mwEmbed/tree/master/modules/Widevine

which is not needed in order for the library to properly function.
I have written to the tech lead for the mwembed project asking that they remove this directory and for now, am removing it during the packaging phase.
This reduced the package to 165M[!] which is quite a substantial difference.
You will get the update when 11.2.0 becomes stable, I am running the final sanity tests as we speak.

Thanks,

**Comment by jessp01** [comment]
New stable [11.2.0] released and includes a much smaller package.
Thanks again for reporting.
