### ISSUE TITLE
Problem getting operational kaltura-sphinx and memecached

### ISSUE THREAD

**Issue by salaroglio** [kaltura/platform-install-packages#514]
Hi everyone,
first of all i apologize if this is not the correct place where to ask help.

I did a installation of Centos 7 adding gui gnome using the install wizard of centos.
then i tried to install kaltura following this guide
https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md 

i opened firewall ports, disable seLinux, configured postfix and installed MariaDB.
when i run /opt/kaltura/bin/kaltura-config-all.sh
i received an error:connection failed to localhost:9312 [MYSQL via TCP]

i tried as a root mysql -uroot -pxxx h127.0.0.1 -P9312 and i receive an error
Can't connect to MySQL server on '127.0.0.1' (111)

Another issue is that memcached seems not to be operational. it fails to start.

Many thanks in advance.

Carlo Salaroglio

**Comment by jessp01** [comment]
Hello @salaroglio,

Sphinx does not require a user and passwd when connecting.
mysql -h127.0.0.1 -P9312
should work.
If it does not, then start by checking the log under /opt/kaltura/log/sphinx/kaltura_sphinx_searchd.log
For memcache, the log also needs to be checked.
To get the logs, use:
journalctl  _SYSTEMD_UNIT=memcached.service

it might also help to have:
OPTIONS="-l 127.0.0.1 -vv" 
in /etc/sysconfig/memcached to increase verbosity

Once you've checked all these, please post at forum.kaltura.org with all the info.
I am closing this issue since we'd rather use the github issues section exclusively for bug reports rather than specific ENV issues.

Thanks,
