### ISSUE TITLE
Studio Issue in 11.10.0

### ISSUE THREAD

**Issue by smartdrive** [kaltura/platform-install-packages#531]
11.10.0 -> Installation without any errors, sanity check all green on CentOS 6.7

Minor Issue:
I can't edit all default players. The editor doesn't load them and shows an endless spinner instead.  Creating a new Player works well.

Regards,
Michael

**Comment by jessp01** [comment]
Hi Michael,

Thanks for you report.
Can you please run:

\# kaltlog
from the shell while making the request and let me know what errors you see? in addition, open the devtools on your browser and look at both the "Console" and "Network" tabs for errors and report these as well.

In general, so long as you can create new players and work with them, I don't consider this fatal but nonetheless, would like to find the root cause.

Thanks,

**Comment by smartdrive** [comment]
Hi Jess,

No Errors in DevTools but Kaltlog shows something related to this issue:

[error] [client _xx.xx.xx.xx_] File does not exist: /opt/kaltura/apps/studio/v2.0.3/templates/.html, referer: http://_my.domain.de_/apps/studio/v2.0.3/index.html

I agree to consider this as not fatal - you may close this here.

Thank you Jess
Michael
