### ISSUE TITLE
kaltura-{base|batch}-config are unnecessarily murdered on debian

### ISSUE THREAD

**Issue by liorkesos** [kaltura/platform-install-packages#538]
The gods have woken and the wrath of them is upon you
How? How? Could you have let this happen
Are rpms the only viable package for thy oh jess?
Seriously add an if so kaltura-base-config and kaltura-batch-config don't croak when they don't have an rpm to query.
Maybe querying for the existance of $APP_DIR/configurations/batch/batch.ini might be better for someone insane enough to build it independently or something...

**Comment by jessp01** [comment]
Not sure I understand what you mean.
In order to reconfigure on deb:
\# dpkg-reconfigure kaltura-base
\# dpkg-reconfigure kaltura-front
\# dpkg-reconfigure kaltura-batch

If you have any additional general questions, please post on forum.kaltura.org, I'd like to keep the Github issues section exclusively for bug reports.

Thanks,

**Comment by liorkesos** [comment]
This is a bug.
when running kaltura-batch.config.sh on ubuntu Iget
```./kaltura-batch-config.sh 
./kaltura-batch-config.sh: line 25: rpm: command not found
Skipping as kaltura-batch is not installed.```

**Comment by liorkesos** [comment]
don't seem to have the ability to reopen bug - so just fyi
