### ISSUE TITLE
DWH Analytic doesnt work

### ISSUE THREAD

**Issue by hunterist** [kaltura/platform-install-packages#540]
These are steps we debuged. I dont know how to fix it.
Could you help resolving? Thanks

**1. Checking DWH status from sanity.**
> /opt/kaltura/bin/kaltura-sanity.sh

Result:
```
[DWH cycle] [FAILED, RC: 255] - [28.984485894]
[Upload content kaltura_logo_animated_green.flv] [PASSED, RC: 0] - [.753096015]
[Upload bulk using CSV] [PASSED, RC: 0] - [.350577977]
[Upload bulk using XML] [PASSED, RC: 0] - [.300775380]
[Create player] [PASSED, RC: 0] - [.254160661]
[Generate thumb] [PASSED, RC: 0] - [.371098942]
[Delete partner] [PASSED, RC: 0] - [.472207893]
[Red5 file upload] [FAILED, RC: 2] - [.053820281]
```

**2. Checking DWH from report sql.**

> less /tmp/kaltura-dev-reportme.10_05_2016.sql

Result:
`INSERT INTO csi_log VALUES(NULL,'DWH cycle','kaltura-dev',1462876348,"Sent event [KalturaStatsEventType::WIDGET_LOADED] Sent event [KalturaStatsEventType::MEDIA_LOADED] Sent event [KalturaStatsEventType::PLAY] Sent event [KalturaStatsEventType::PLAY_REACHED_25] Sent event [KalturaStatsEventType::PLAY_REACHED_50] Sent event [KalturaStatsEventType::PLAY_REACHED_75] Sent event [KalturaStatsEventType::PLAY_REACHED_100] Executing [/usr/sbin/logrotate -f /etc/logrotate.d/kaltura_apache]Reloading httpd: log rotated Executing [su root -c /opt/kaltura/dwh/etlsource/execute/etl_hourly.sh -p /opt/kaltura/dwh -k /opt/kaltura/pentaho/pdi/kitchen.sh ] OK Executing [su root -c /opt/kaltura/dwh/etlsource/execute/etl_update_dims.sh -p /opt/kaltura/dwh -k /opt/kaltura/pentaho/pdi/kitchen.sh] OK Executing [su root -c /opt/kaltura/dwh/etlsource/execute/etl_daily.sh -p /opt/kaltura/dwh -k /opt/kaltura/pentaho/pdi/kitchen.sh] OK Reported wrong total count []",255,25.278971595,'11.10.0');`

I rerun /opt/kaltura/bin/kaltura-dwh-config.sh but no lucky
[kaltura-dev-reportme.10_05_2016.sql.zip](https://github.com/kaltura/platform-install-packages/files/256993/kaltura-dev-reportme.10_05_2016.sql.zip)

Thanks

**Comment by emostoyanov** [comment]
Hi, same here. I was not able to resolve it either. So far...

**Comment by jessp01** [comment]
Hello,

The DWH test sometimes fails during sanity due to timing, it does not necessarily mean something is wrong.
If there is still an issue and you do not see Analytics data, I suggest you first upgrade to the latest version and then, follow troubleshooting steps here:
https://github.com/kaltura/platform-install-packages/blob/Kajam-11.21.0/doc/kaltura-packages-faq.md#analytics-issues

And post the results on forum.kaltura.org.
Due note that views/plays done from within KMC are not included in Analytics on purpose, only view done from external player embeds will be counted.
We'd like to keep the Github issues section for bug reporting rather than general troubleshooting.
