### ISSUE TITLE
kaltura-front-config.sh FAILED with: 45627 on line 296

### ISSUE THREAD

**Issue by lopar** [kaltura/platform-install-packages#553]
Got this installation error via install on localhost.localdomain CentOS7 without ssl.
After that I see index page but cannot login to admin console.

**Comment by jessp01** [comment]
Hello,

This is not enough info in order to help you fix it.
Start by looking at /opt/kaltura/bin/kaltura-front-config.sh on line 296 to see what it actually does. Since you didn't specify your Kaltura version, I can't tell.

We'd like to keep the issues section for specific bug reports and not general troubleshooting discussions.
Please open a thread at forum.kaltura.org with the entries from the log, as well as a full description of your ENV: Linux distro,
Kaltura version, is this a cluster or a single machine, the full output when running the configure script and any additional relevant info.

Thanks,
