### ISSUE TITLE
New Install: Videos Don't Play

### ISSUE THREAD

**Issue by ecrist** [kaltura/platform-install-packages#561]
We have just installed Kaltura in a non-SSL standalone mode on a Cent OS 7 system.  We are able to upload and download videos, but we are unable to play back video from the web interface.  We can see controls, and the saved screen shot appears, but pressing "play" doesn't seem to have any effect.  The video timing all shows 0:00, as well.

**Comment by jessp01** [comment]
Hello,

More info is needed:
Start by running:
\# source /etc/profile.d/kaltura_base.sh
\# kaltlog 
from the kaltura server shell and look for errors outputted to STDOUT.
In parallel, use your browser's dev tools and look under both the "Console" and "Network" tabs.
It would also help if you added a link to an embed sample of such a video so we can look.

Since we'd rather leave the Github issues section for bug reports and not for general troubleshooting and questions, I am closing the issue. Please post at forum.kaltura.org instead and include all details, including the exact CE version you deployed.

Thanks,
