### ISSUE TITLE
Upgrade produces PHP errors

### ISSUE THREAD

**Issue by GusDenton** [kaltura/platform-install-packages#576]
Hi Kalturians
We have just run the YUM UPGRADE KALTURA command and ended up with pages of PHP fatal errors in KALTLOG
Current php version is 5.3.3
`PHP Fatal error:  Class 'KalturaSerializableStream' not found in /opt/kaltura/app/infra/log/KalturaLogFactory.php on line 59

--
==> /opt/kaltura/log/kaltura_apache_errors_ssl.log <==
[Mon Nov 28 17:18:09 2016] [error] [client 202.9.42.179] PHP Fatal error:  Class 'kLoggerCache' not found in /opt/kaltura/app/alpha/bootstr                  ap.php on line 18, referer: https://www.aftrs.edu.au/award-courses/2017_advanced_diploma_in_visual_effects/5416

--
==> /opt/kaltura/log/batch/kschedulehelper-0-2016-11-28.log <==
PHP Fatal error:  Class 'KalturaSerializableStream' not found in /opt/kaltura/app/infra/log/KalturaLogFactory.php on line 59

--
==> /opt/kaltura/log/batch/kschedulehelper-0-2016-11-28.log <==
PHP Fatal error:  Class 'KalturaSerializableStream' not found in /opt/kaltura/app/infra/log/KalturaLogFactory.php on line 59

==> /opt/kaltura/log/kaltura_apache_errors_ssl.log <==
[Mon Nov 28 17:18:30 2016] [error] [client 172.20.1.13] PHP Fatal error:  Class 'kLoggerCache' not found in /opt/kaltura/app/api_v3/bootstr                  ap.php on line 30, referer: https://webkaltura.aftrs.edu.au/flash/kmc/v5.23.2/kmc.swf

--
==> /opt/kaltura/log/batch/kschedulehelper-0-2016-11-28.log <==
PHP Fatal error:  Class 'KalturaSerializableStream' not found in /opt/kaltura/app/infra/log/KalturaLogFactory.php on line 59

--
==> /opt/kaltura/log/batch/kschedulehelper-0-2016-11-28.log <==
PHP Fatal error:  Class 'KalturaSerializableStream' not found in /opt/kaltura/app/infra/log/KalturaLogFactory.php on line 59

==> /opt/kaltura/log/kaltura_apache_errors_ssl.log <==
[Mon Nov 28 17:19:00 2016] [error] [client 172.20.1.13] PHP Fatal error:  Class 'kLoggerCache' not found in /opt/kaltura/app/api_v3/bootstr                  ap.php on line 30, referer: https://webkaltura.aftrs.edu.au/flash/kmc/v5.23.2/kmc.swf

--
==> /opt/kaltura/log/batch/dbcleanup-0-2016-11-28.log <==
PHP Fatal error:  Class 'KalturaSerializableStream' not found in /opt/kaltura/app/infra/log/KalturaLogFactory.php on line 59`

We have upgraded an old version of Kaltura which only had HTML5 V1.7 support. 
Firstly we were able to install the HTML5 player as per instructions two version 2.5, 
but then we got media could not be found errors from the HTML5 player even when the streamer type in the URL was set to http. With our setup we have extensive metadata stored in XML files and a custom metadata schema.

We are really stuck here.. our other option is to try and graft the media, metadata schema xml, category structure and players to a functioning install (which we have) and i would prefer to upgrade the existing Kaltura in situ as I think this would also present huge issues as well.
I would really appreciate any help as we are using kaltura in a mission critial fashion

**Comment by jessp01** [comment]
Hello @GusDenton,

I am a bit confused.. you said "We have upgraded an old version of Kaltura which only had HTML5 V1.7 support.", which server version did you upgrade from? I am asking because non of the CE versions released using RPMs and debs had such an old version, which leads me to believe your server ran a much older CE version [first RPM release was for CE 9, current stable is 12.5.0]. If this is the case, the upgrade process is a bit complex but we do have instructions here:
https://github.com/kaltura/platform-install-packages/tree/Lynx-12.6.0/doc/kaltura-updater

Please clarify what version you upgraded from and what steps you've taken in order to perform the upgrade and we can continue from there.

**Comment by GusDenton** [comment]
Hi @jessp01 
Sorry i am quite a newbie on Kaltura CE..
What you say makes sense, we have rolled the update back to our previous state.
The question for me now is
having got the v2 html5 player installed and being served I need to resolve the "No source video was found" error from the player.

I have suspected that this is the streamer type and thought that upgrading the Red5 server is the next thing to do
OR
upgrade the complete Kaltura server...

If I can fix the media error as a stop gap I would be very happy as this is a production environment and we need a solution now.

Regarding the manual upgrade process you have refered me to: I think that I need a little more clarity about the instructions provided and where one runs the code in the supplied git repo.
As I say I am a newbie.
Thanks for your help 
Angus

**Comment by jessp01** [comment]
Hi @GusDenton,

I'm afraid I still don't understand what CE version you're running... which one is it?
You cannot use the latest version of the HTML5 player with very old versions of the server, it will not work.

As for the upgrade instructions, please post any specific questions on our forum at forum.kaltura.org and I'll be happy to answer them. 
I am closing the issue since we prefer addressing general questions in the forum, keeping the GitHub issues sections for general bug reports exclusively.

**Comment by GusDenton** [comment]
@jessp01 I cannot find a version number in the KMC, ADMIN Console or any obvious read me file in `/opt/kaltura` directory
All I can tell you from the deploy log is that it was built July 1 2013
