### ISSUE TITLE
CentOS 7 and PHP 7 support 

### ISSUE THREAD

**Issue by lelikg** [kaltura/platform-install-packages#586]
Hi, the Centos 7 support has been great!
How about PHP 7 support on CentOS 7? 
From what I could see, all is needed is to get rid of php-pecl-memcached dependency, perhaps a few others, but it seems minor.
What say you @jessp01

**Comment by jessp01** [comment]
Hi @lelikg,

Code wise, the Kaltura Server fully supports PHP7. See my post about that here: https://blog.kaltura.com/announcing-kaltura-support-for-php7/
When porting to PHP 7, I also built Ubuntu 14.04 compatible PHP 7 deb packages for all needed PHP deps [Apache module, CLI and all needed extensions, including memcache [do not confuse the memcahe extension with the memcachd extension, the memcache extension is needed for Kaltura Server, the memcached extension is not].

That said, RHEL/CentOS 7's official repos do not provide PHP 7 packages and, unlike the deb packaging format, RPM does not allow specifying logical ORs when declaring dependencies. Therefore, with RPM, one cannot say a package depends on php5|php7.
There are several none official PHP 7 repos that can work with RHEL/CentOS, both 7 and 6, for example, see https://webtatic.com/packages/php70/. However, as you can also see, the package names are different than their official RHEL/CentOS parallels and are prefixed with php70w, since RPM does not allow logical ORs for dependencies, this is a problem.

Also, installing the Kaltura Server packages which depend on the PHP packages from the official repos and then installing alternative PHP packages from say the webtatic repos, will not work since the PHP 7 packages declare conflicts with the PHP 5 [5.4 for RHEL/CentOS7] packages.
So YUM will complain with:
Error: php70w-common conflicts with php-common

If you want to build RPM packages [or just compile your own PHP 7 onto a different prefix, wihtout packaging as RPM] that install onto different paths and hence do NOT conflict with the official PHP 5 packages, you certainly can and the server code will run but you will not be able to remove the PHP 5 packages with YUM since the kaltura RPMs depend on them. You could remove them manually with rpm commands but I highly recommend that you do not, for obvious reasons.

**Comment by lelikg** [comment]
@jessp01 simple and elegant solution, thanks!

**Comment by lelikg** [comment]
Update:
After some digging I found that you actually can update to PHP7 without breaking dependencies:


```
wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
wget http://rpms.remirepo.net/enterprise/remi-release-7.rpm
rpm -Uvh remi-release-7.rpm epel-release-latest-7.noarch.rpm
subscription-manager repos --enable=rhel-7-server-optional-rpms

yum install yum-utils
yum-config-manager --enable remi-php71

yum update

php -v 
```

Taken from https://blog.remirepo.net/post/2016/12/05/Install-PHP-7.1-on-CentOS-RHEL-or-Fedora

**Comment by jessp01** [comment]
Just for the benefit of other people hitting this issue:
Yes, the Remi repo uses the same package names for PHP 7 as the official PHP package names in the official repo. This is why a smooth upgrade is possible.
This is a fine solution for those who do not need both PHP 5 and PHP 7 packages to co-exist on the same box. As long as your server only runs Kaltura, this is OK.
It is important to note that these are not official RedHat packages and so, those who pay RedHat for support, will not get support on these packages from RedHat. In general, the quality of packages in the Remi repos is good so, setting official distro support aside, it should be fine to use them.
