### ISSUE TITLE
Installing Kaltura DB on RDS, Super User Privilege error

### ISSUE THREAD

**Issue by kodisj** [kaltura/platform-install-packages#589]
Hi,
  I am trying to install Kaltura DBs in RDS, I could not succeed, it is throwing mysql error for super user privilege, i enabled the log_bin_trust_function_creators =1, still no luck..  Could some one please help me in this.

-Kodis

**Comment by jessp01** [comment]
Hello @kodisj,

In order to deploy Kaltura Server, one needs a MySQL user that would allow:
- The creation of databases
- The creation of DB users
Also, the following MySQL settings are needed:
```
lower_case_table_names = 1
innodb_file_per_table
innodb_log_file_size=32M [or higher]
open_files_limit = 20000 [or higher]
max_allowed_packet = 16M [or higher]
```

You should be able to set up an RDS instance that allows these actions. Take a look at the RDS documentation to determine how.

I believe you should be able to use a MySQL client with your current RDS master user and run:
```
mysql> CREATE USER 'superuser'@'%' IDENTIFIED BY 'YOURPASSWD';
mysql> GRANT ALL ON `%`.* TO superuser@`%`
```
then, 'superuser' should be able to create the needed DBs and kaltura DB users.
For setting the MySQL settings, which would usually be done by editing my.cnf, see http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithParamGroups.html

For additional questions, please post at forum.kaltura.org since we prefer to use the GitHub issues section for bug reports only, rather than general question.

Thanks,
