### ISSUE TITLE
Docker container exists with code 139

### ISSUE THREAD

**Issue by ciliehub** [kaltura/platform-install-packages#646]
For development reasons I need a specific version of Kaltura server. (13.19). I skipped the debug report, because it is not (yet) relevant at the point where I'm stuck.

I did a docker pull:

`docker pull kaltura/server:Mercury-13.19.0`

Then I tried to `exec` the command given in [https://github.com/kaltura/platform-install-packages/blob/master/doc/install-docker.md#start-kaltura-container](https://github.com/kaltura/platform-install-packages/blob/master/doc/install-docker.md#start-kaltura-container), only with the tag addition:

`docker run -d --name=kaltura -p 80:80 -p 443:443 -p 1935:1935 -p 88:88 -p 8443:8443 kaltura/server:Mercury-13.19.0`

After that, nothing happens, no container is running, it exited:
`29e2bc7bbd69        kaltura/server:Mercury-13.19.0   "/sbin/init"             6 seconds ago       Exited (139) 5 seconds ago                       kaltura`

Unfortunately, `docker logs 29e2bc7bbd69`  yields nothing.

How can I make this work?

**Comment by jessp01** [comment]
Hi @ciliehub,

I just ran the very same command:
```
# docker run -d --name=kaltura -p 80:80 -p 443:443 -p 1935:1935 -p 88:88 -p 8443:8443 kaltura/server:Mercury-13.19.0
```
and it worked just fine so I'm afraid more info is needed. What's the full output you're getting when running it?

Also, note that while by specifying `kaltura/server:Mercury-13.19.0` you will get the RPMs from the 13.19.0, `/etc/yum.repos.d/kaltura.repo` is set up like so:
> baseurl = http://installrepo.kaltura.org/releases/latest/$releasever/RPMS

And http://installrepo.kaltura.org/releases/latest always points to the last stable version [14.15.0 at present time] and so, if you were to run `yum update`, your container would be upgraded. You can edit `/etc/yum.repos.d/kaltura.repo` and replace `latest` with `13.19.0` in order to prevent that from happening.

**Comment by ciliehub** [comment]
Thanks for your quick answer. Just found out: it has nothing to do with Kaltura.

I didn't tell you I am running Docker within an Arch linux environment (wasn't suspecting this to be a kind of issue)

[https://unix.stackexchange.com/questions/478387/running-a-centos-docker-image-on-arch-linux-exits-with-code-139](https://unix.stackexchange.com/questions/478387/running-a-centos-docker-image-on-arch-linux-exits-with-code-139)

For running CentOS docker guests within Arch you need to set a kernel parameter.

You may close the issue.

**Comment by jessp01** [comment]
Cheers, @ciliehub. Closing.
