### ISSUE TITLE
Transcoding not working 

### ISSUE THREAD

**Issue by NirangaKumarasinghe** [kaltura/platform-install-packages#680]
I tried  uploading mp4 format file to the system. After it is completed uploading it changes to state "Converting" , then it stays in that state forever.Can you guys please help me on this ?

**Comment by adbias** [comment]
Got a similar issue but you should check your logs.
Can you check if your kaltura-batch process is running and has enough memory?

**Comment by jessp01** [comment]
Hello all,

Please see https://forum.kaltura.org/t/files-fail-to-ingest-trapped-in-convert-step/10052/2

Feel free to post follow up questions on the forum. I'm closing the issue since we'd like to use the repo's `issues` section for bug reporting only (as opposed to troubleshooting/general questions).

Thanks,
